<?

// Edit these values for whatever you want the font name and copyright to be
// when writing FD or BDF fonts.
$fontname = "My VG Font";
$copyright = "This font file was generated by FEIDIAN.";

?>